name: Html
options:
  bundleIdPrefix: co.pointfree
  indentWidth: 2
  tabWidth: 2
  usesTabs: false
targets:
  Html:
    deploymentTarget:
      iOS: 8.0
      macOS: '10.10'
      tvOS: 9.0
      watchOS: 2.0
    info:
      path: Info.plist
    platform: [macOS, iOS, tvOS, watchOS]
    scheme:
      testTargets: ['HtmlTests_${platform}']
    settings:
      SWIFT_VERSION: 5.0
    sources: [Sources/Html]
    type: framework
  HtmlTests:
    dependencies: [{target: 'Html_${platform}'}]
    deploymentTarget:
      iOS: 10.0
      macOS: '10.10'
      tvOS: 10.0
    platform: [macOS, iOS, tvOS, watchOS]
    settings:
      SWIFT_VERSION: 5.0
    sources:
      - path: Tests/HtmlTests
    type: bundle.unit-test
  HtmlSnapshotTesting:
    dependencies:
      - target: 'Html_${platform}'
      - framework: SnapshotTesting.framework
        implicit: true
    deploymentTarget:
      iOS: 10.0
      macOS: '10.10'
      tvOS: 10.0
    info:
      path: Info.plist
    platform: [macOS, iOS, tvOS]
    settings:
      ENABLE_BITCODE: false
      SWIFT_VERSION: 5.0
    scheme:
      testTargets: ['HtmlSnapshotTestingTests_${platform}']
    sources: [Sources/HtmlSnapshotTesting]
    type: framework
  HtmlSnapshotTestingTests:
    dependencies: [{target: 'HtmlSnapshotTesting_${platform}'}]
    deploymentTarget:
      iOS: 10.0
      macOS: '10.10'
      tvOS: 10.0
    platform: [macOS, iOS, tvOS]
    settings:
      SWIFT_VERSION: 5.0
    sources:
      - path: Tests/HtmlSnapshotTestingTests
        excludes:
          - '__Snapshots__'
    type: bundle.unit-test
