version: 2

jobs:
  build:
    macos:
      xcode: "9.4.1"

    steps:
      - checkout

      - run:
          name: Mac Info
          command: system_profiler SPSoftwareDataType

      - run:
          name: Print Devices
          command: instruments -s devices

      - run:
          name: Install xcodegen
          command: brew install xcodegen

      - run:
          name: Run macOS tests
          command: make test-macos
          environment:
            SNAPSHOT_ARTIFACTS: $CIRCLE_ARTIFACTS

      - run:
          name: Run Swift tests
          command: make test-swift
          environment:
            SNAPSHOT_ARTIFACTS: $CIRCLE_ARTIFACTS
