version: 2

jobs:
  build:
    macos:
      xcode: "10.1.0"

    steps:
      - checkout

      - run:
          name: Mac Info
          command: system_profiler SPSoftwareDataType

      - run:
          name: Simulator Info
          command: instruments -s devices

      - run:
          name: Check out dependencies
          command: git submodule update --init --recursive

      - run:
          name: Run Swift tests
          command: make test-swift
          environment:
            SNAPSHOT_ARTIFACTS: /tmp/__SnapshotArtifacts__

      - store_artifacts:
          path: /tmp/__SnapshotArtifacts__
